### PR TITLE
Add initial implementation of the file dropper

### PR DESCRIPTION
**Pull request by FrozenAlex**
I ran prettier on it and it added too many formatting changes. Not the prettiest code out there but does the job

### CODE REVIEW

**Comment by WombleWoo7547** [comment]
lgtm

**Comment by Lauriethefish** [comment]
Mostly looking good although is there a reason why the mod importing logic in `ModManager` is reimplemented in `DeviceModder`? Ideally `DeviceModder` shouldn't involve mod installing and should just be installation management.

**Comment by Lauriethefish** [comment]
Mod importing logic now moved to `ModManager`.
Needs a mod import queue to avoid race conditions where two separate drag-drops could cause two separate agent requests to be made simultaneously, which it will not handle gracefully.

**Comment by Lauriethefish** [comment]
Now lgtm

**Pull request merged**
