### PR TITLE
Animated background

### PR DESCRIPTION
**Pull request by XoToM**
Added an animated background with Beat Saber blocks falling. The code is a bit ugly at the moment, and I will try to rewrite it as soon as I can, so you don't have to merge this yet.

### CODE REVIEW

**Comment by Futuremappermydud** [comment]
Any preview to add?

**Comment by Lauriethefish** [comment]
image

**Comment by Lauriethefish** [comment]
Rebased

**Comment by XoToM** [comment]
Finished rewriting the animations, added new blocks, fixed bugs, and made blocks spawn randomly when the website starts.

**Comment by XoToM** [comment]
Also the amount of blocks on screen will now change depending on how big the screen is. Here is a screenshot of the new version.
image

**Comment by Lauriethefish** [comment]
Main container missing side padding on android

**Comment by Lauriethefish** [comment]
Fixed that, LGTM

**Pull request merged**
